apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Komp3"
  description: "Komponent 3 testowy też"
  annotations:
    github.com/project-slug: IridiumOxide/Komp3
spec:
  type: documentation
  lifecycle: experimental
  owner: "group:default/guests"